version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['update: packages 📦']
    commit-message:
      prefix: "chore"
    schedule:
      interval: 'monthly'
      time: '08:00'
      timezone: 'Europe/Rome'
