version: 2.1

# --- define orbs (a reusable packages of CircleCI configuration)
orbs:
  codecov: codecov/codecov@1.0.2

# --- define aliases
aliases:
  - &restore-cache-deps
    key: dependency-cache-{{ checksum "package.json" }}-2
  - &save-cache-deps
    key: dependency-cache-{{ checksum "package.json" }}-2
    paths:
      - node_modules

# --- define base job's config
defaults: &defaults
  working_directory: ~/postcss-config
  docker:
    - image: circleci/node:lts

# --- define jobs
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache-deps
      - run: npm install npm@latest
      - run: npm install
      - save_cache: *save-cache-deps
      - persist_to_workspace:
          root: ~/postcss-config
          paths:
            - '*'

  check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-config
      - run:
          command: |-
            npm run check:config
            npm run check:src
            npm run lint:src

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-config
      - run: npm run test

  coverage:
    <<: *defaults
    steps:
      - codecov/upload:
          file: coverage/index.html

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/postcss-config
      - run: npm run build

# --- workflows
workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - check:
          requires:
            - setup
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - test
      - build:
          requires:
            - check
            - test
