name: Tests

on:
  push:
    branches:
      - 'stable'
  pull_request:
    branches:
      - 'stable'

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['16.x', '18.x']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build the artifact'
        run: npm run build

      - name: 'Run TSC compiler, linters and tests'
        run: |
          npm run check
          npm run test:coverage
        env:
          CI: true

      - name: 'Compile CSS and SCSS with postcss-cli'
        run: npm run compile:css

      - name: 'Upload test coverage to Coveralls'
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
